version: "3"

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    restart: always
    networks:
      - phpwork

  php:
    image: hyj1412/php:${PHP_VERSION}-fpm-alpine
    container_name: php
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
    restart: always
    networks:
      - phpwork

  nginx:
    image: hyj1412/nginx:${NGINX_VERSION}-alpine
    container_name: nginx
    volumes:
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${SOURCE_DIR}:/var/www/html:rw
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    restart: always
    networks:
      - phpwork

  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_DATA_DIR}:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - phpwork

networks:
  phpwork:
