version: "3"

services:
  mysql:
    image: mysql:5
    container_name: mysql5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks:
      - cloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "1080:80"
    depends_on:
      - mysql
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "${TRUSTED_DOMAINS}"
    volumes:
      - ${NEXTCLOUD_DATA_DIR}:/var/www/html/data
    restart: always
    networks:
      - cloud

networks:
  cloud:
