version: "3"

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    restart: always
    networks:
      - drupal7

  drupal7:
    image: drupal:7
    container_name: drupal7
    ports:
      - "${DRUPAL_HTTP_PORT}:80"
    depends_on:
      - mysql
    volumes:
      - ${DRUPAL_MODULE_PATH}:/var/www/html/sites/all/modules
      - ${DRUPAL_THEME_PATH}:/var/www/html/sites/all/themes
      - ${DRUPAL_CONF_PATH}:/var/www/html/sites/default
    restart: always
    networks:
      - drupal7

networks:
  drupal7:
